kind: Deployment
apiVersion: apps/v1
metadata:
  name: redisslave-dep
spec:
  selector:
    matchLabels:
      app: gbchn
      release: gbchn
      role: slave
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gbchn
        release: gbchn
        role: slave
        tier: backend
    spec:
      containers:
      - name: gbchn
        image: "gcr.io/google_samples/gb-redisslave:v3"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: dns

